/*
Copyright (C) 1997-2001 Id Software, Inc.
Copyright (C) 2023-2024 starfrost

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/
#pragma once

// snd_loc.h -- private sound functions

typedef struct
{
	int32_t 		left;
	int32_t 		right;
} portable_samplepair_t;

typedef struct
{
	int32_t 		length;
	int32_t 		loopstart;
	int32_t 		speed;			// not needed, because converted on load?
	int32_t 		width;
	int32_t 		stereo;
	uint8_t		data[1];		// variable sized
} sfxcache_t;

typedef struct sfx_s
{
	char 		name[MAX_QPATH];
	int32_t 		registration_sequence;
	sfxcache_t	*cache;
	char 		*truename;
} sfx_t;

// a playsound_t will be generated by each call to S_StartSound,
// when the mixer reaches playsound->begin, the playsound will
// be assigned to a channel
typedef struct playsound_s
{
	struct playsound_s	*prev, *next;
	sfx_t		*sfx;
	float		volume;
	float		attenuation;
	int32_t 		entnum;
	int32_t 		entchannel;
	bool	fixed_origin;	// use origin field instead of entnum's origin
	vec3_t		origin;
	uint32_t	begin;			// begin on this sample
} playsound_t;

typedef struct
{
	int32_t 		channels;
	int32_t 		samples;				// mono samples in buffer
	int32_t 		submission_chunk;		// don't mix less than this #
	int32_t 		samplepos;				// in mono samples
	int32_t 		samplebits;
	int32_t 		speed;
	uint8_t		*buffer;
} dma_t;

// !!! if this is changed, the asm code must change !!!
typedef struct
{
	sfx_t		*sfx;			// sfx number
	int32_t 		leftvol;		// 0-255 volume
	int32_t 		rightvol;		// 0-255 volume
	int32_t 		end;			// end time in global paintsamples
	int32_t 		pos;			// sample position in sfx
	int32_t 		looping;		// where to loop, -1 = no looping OBSOLETE?
	int32_t 		entnum;			// to allow overriding a specific sound
	int32_t 		entchannel;		//
	vec3_t		origin;			// only use if fixed_origin is set
	vec_t		dist_mult;		// distance multiplier (attenuation/clipK)
	int32_t 		master_vol;		// 0-255 master volume
	bool	fixed_origin;	// use origin instead of fetching entnum's origin
	bool	autosound;		// from an entity->sound, cleared each frame
} channel_t;

typedef struct
{
	int32_t 		rate;
	int32_t 		width;
	int32_t 		channels;
	int32_t 		loopstart;
	int32_t 		samples;
	int32_t 		dataofs;		// chunk starts this many bytes from file start
} wavinfo_t;


/*
====================================================================

  SYSTEM SPECIFIC FUNCTIONS

====================================================================
*/

// initializes cycling through a DMA buffer and returns information on it
bool SNDDMA_Init(void);

// gets the current DMA position
int32_t 	SNDDMA_GetDMAPos(void);

// shutdown the DMA xfer.
void	SNDDMA_Shutdown(void);

void	SNDDMA_BeginPainting (void);

void	SNDDMA_Submit(void);

//====================================================================

#define	MAX_CHANNELS			32
extern	channel_t   channels[MAX_CHANNELS];

extern	int32_t 	paintedtime;
extern	int32_t 	s_rawend;
extern	vec3_t	listener_origin;
extern	vec3_t	listener_forward;
extern	vec3_t	listener_right;
extern	vec3_t	listener_up;
extern	dma_t	dma;
extern	playsound_t	s_pendingplays;

#define	MAX_RAW_SAMPLES	8192
extern	portable_samplepair_t	s_rawsamples[MAX_RAW_SAMPLES];

extern cvar_t* s_volume;
extern cvar_t* s_nosound;
extern cvar_t* s_loadas8bit;
extern cvar_t* s_khz;
extern cvar_t* s_show;
extern cvar_t* s_mixahead;
extern cvar_t* s_testsound;
extern cvar_t* s_primary;

wavinfo_t GetWavinfo (char *name, uint8_t *wav, int32_t wavlength);

void S_InitScaletable (void);

sfxcache_t *S_LoadSound (sfx_t *s);

void S_IssuePlaysound (playsound_t *ps);

void S_PaintChannels(int32_t endtime);

// picks a channel based on priorities, empty slots, number of channels
channel_t *S_PickChannel(int32_t entnum, int32_t entchannel);

// spatializes a channel
void S_Spatialize(channel_t *ch);
